### ISSUE TITLE
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:3789: error: (-215:Assertion failed) !dsize.empty() in function 'cv::hal::resize'

### ISSUE THREAD

**Issue by Cokeheart** [biegert/ComfyUI-CLIPSeg#19]
!!! Exception during processing !!!
Traceback (most recent call last):
File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\clipseg.py", line 154, in segment_image
heatmap_resized = resize_image(heatmap, dimensions)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\clipseg.py", line 44, in resize_image
return cv2.resize(image, dimensions, interpolation=cv2.INTER_LINEAR)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
![微信图片_20240403220839](https://github.com/biegert/ComfyUI-CLIPSeg/assets/124596170/001360f2-c343-43cd-8815-dbc235cebdd0)

**Comment by shaoheming** [comment]
i got this error too...

**Comment by Cokeheart** [comment]
> i got this error too...

"I redeployed comfyui and installed CLIPSeg separately, which resolved the issue. Next, I plan to install and troubleshoot each plugin one by one

**Comment by dimroce** [comment]
same here, So is it due to some node upgrades?

**Comment by ssuukk** [comment]
me too!

**Comment by wer5245** [comment]
重装插件，然后和3699错误一样的步骤改代码，再试试

**Comment by yincangshiwei** [comment]
> 重装插件，然后和3699错误一样的步骤改代码，再试试
怎么改

**Comment by xuxucca** [comment]
Try installing transformers up to 4.36.0 if you can!or lower。使用较低版本的 transformers可以解决这个问题。

**Comment by shaoheming** [comment]
https://blog.csdn.net/JuMengXiaoKeTang/article/details/137383951

**Comment by GalaxyTimeMachine** [comment]
> https://blog.csdn.net/JuMengXiaoKeTang/article/details/137383951

Thank you, this resolved it for me!  :)

**Comment by Godorox** [comment]
> https://blog.csdn.net/JuMengXiaoKeTang/article/details/137383951

I tried this solution but it doesn't work. I didn't understand the part: "cv 4.9.0, transformers 4.39.2 works well". Has anyone found another solution?

> Try installing transformers up to 4.36.0 if you can! or lower. Using lower versions of transformers can solve this problem.

How can I do this?

**Comment by GalaxyTimeMachine** [comment]
> > https://blog.csdn.net/JuMengXiaoKeTang/article/details/137383951
> 
> I tried this solution but it doesn't work. Has anyone found another solution?
> 
> > Try installing transformers up to 4.36.0 if you can! or lower. Using lower versions of transformers can solve this problem.
> 
> How can I do this?

The only change I needed to make was to the clipseg.py file. Just make that change and it should work.

Basically, edit custom_nodes/clipseg.py to this: 
![0c9bc471fb6c4e38a010ea4317364a83](https://github.com/biegert/ComfyUI-CLIPSeg/assets/52193044/e1189a82-1fec-43fa-8f13-02b5ff1901c4)

**Comment by toprakfirat** [comment]
Updating the script didnt work for me

**Comment by wangzixin1** [comment]
低级的错误，作者怎么 能用绝对路径？
OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:3789: error: (-215:Assertion failed) !dsize.empty() in function 'cv::hal::resize'

**Comment by yw-2020** [comment]
!!! Exception during processing!!! OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:3699: error: (-215:Assertion failed) !dsize.empty() in function 'cv::hal::resize'

Traceback (most recent call last):
  File "E:\ComfyUI_WIN\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_WIN\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_WIN\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_WIN\ComfyUI\custom_nodes\clipseg.py", line 154, in segment_image
    heatmap_resized = resize_image(heatmap, dimensions)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_WIN\ComfyUI\custom_nodes\clipseg.py", line 44, in resize_image
    return cv2.resize(image, dimensions, interpolation=cv2.INTER_LINEAR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:3699: error: (-215:Assertion failed) !dsize.empty() in function 'cv::hal::resize'

how to fix??

**Comment by yw-2020** [comment]
> https://blog.csdn.net/JuMengXiaoKeTang/article/details/137383951

thanks, it worked!!!

**Comment by ioritree** [comment]
> https://blog.csdn.net/JuMengXiaoKeTang/article/details/137383951

new problem after changed

Error occurred when executing Bounded Image Crop with Mask:

index is out of bounds for dimension with size 0

**Comment by JulianKingman** [comment]
Looks like this PR fixes it: https://github.com/biegert/ComfyUI-CLIPSeg/pull/18/files
