### ISSUE TITLE
Raise error: (-215:Assertion failed) !dsize.empty() in function 'cv::hal::resize'

### ISSUE THREAD

**Issue by ultimatech-cn** [biegert/ComfyUI-CLIPSeg#9]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipsegnode.py", line 216, in combine_masks
    heatmap_resized = resize_image(heatmap, dimensions)
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipsegnode.py", line 44, in resize_image
    return cv2.resize(image, dimensions, interpolation=cv2.INTER_LINEAR)
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:3699: error: (-215:Assertion failed) !dsize.empty() in function 'cv::hal::resize'

**Comment by ibadmore** [comment]
anyone have any luck with this?

**Comment by longglecc** [comment]
yes, i am luck dog

**Comment by ultimatech-cn** [comment]
updating comfyui and clipseg.
